services:
  todo-api:
    build: todo-api
    image: todo-api
    restart: "no"
    volumes:
      - ./todo-api/:/app
      - ./app-cache/:/app-cache
    ports:
      - "7777-7778:7777"
    depends_on: 
      - database
      - flyway
      - redis

    env_file:
      - project.env
    deploy:
      replicas: 2
    expose:
      - 7777

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:11.1.0
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
    ports:
      - 7800:7800  
      
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379